### PR TITLE
Update Kotlin to 1.4

### PR DESCRIPTION
**Pull request by ajalt**
I didn't enable the [hierarchical MPP structure](https://kotlinlang.org/docs/reference/mpp-share-on-platforms.html#share-code-on-similar-platforms) because it breaks the build due to `platform.posix` libraries not being supported in shared source sets.

### CODE REVIEW

**Comment by rvprasad** [comment]
Currently, using Clikt 2.8.0 with KScript 2.9.3 and Kotlin 1.4.0 causes a NoSuchMethodError (see issue holgerbrandl/kscript#276) due to the use of a method introduced in Kotlin 1.4.  So, any idea when do you plan to release a version of Clikt that is compatible with Kotlin-1.4?  Thanks in advance,

**Comment by ajalt** [comment]
@rvprasad I'm not sure that problem is caused by clikt, but I'll release a new version soon. In the meantime, you can use a snapshot: https://github.com/ajalt/clikt#snapshots

**Comment by rvprasad** [comment]
Based on the information at https://search.maven.org/artifact/com.github.ajalt/clikt/2.8.0/jar, clikt-2.8.0 depends on v1.3.72 of kotlin-stdlib.jar and kotlin-stdlib-common.jar.  Since kscript pulls in dependency using gradle/maven mechanism, I think the inclusion of these dependencies is causing the exception.

Also, on a related note, what's the easiest way to build clikt.jar for just the JVM (without building the native support)?

**Comment by ajalt** [comment]
`./gradlew jvmJar`

**Pull request merged**
