### PR TITLE
Add ability to read option values from files

### LINKED ISSUE #78: Retrieve values from file instead of envvar ?
Hello,

New to Kotlin, I'm building an installer for an app with your tool. I was wondering if it would be possible to retrieve values from a file instead of envvars ? I saw #59 so I could first load my file content as env variables but I would prefer to have access to the file, especially as it's a yaml file with nested values in it.

Any idea on how to implement this use case ?

Global idea is : if values are in the file, use them, and if not prompt for them.

Thanks !

### PR DESCRIPTION
**Pull request by ajalt**
Fixes #78

### CODE REVIEW

**Comment by ajalt** [comment]
@nsteinmetz I implemented configurable file sources for option values. This will allow you to read option values from command line, environment variables, and one or more files. You can also set a default value as ususal if the value doesn't exist in any of those places. 

 I'd love to get your feedback on this design. Does it solve your use case? Do you have any suggestions on naming, structure, or documentation?

 You should be able to add this branch to your project with [JitPack](https://jitpack.io/#ajalt/clikt/configs-SNAPSHOT).

To avoid adding dependencies, I only support java Properties files out of the box, but here's an example of [reading from JSON files](https://github.com/ajalt/clikt/tree/configs/samples/json/src/main/kotlin/com/github/ajalt/clikt/samples/json).

**Comment by CasparKielwein** [comment]
Anything I could do to help move this along?
I could very much use this feature.

**Comment by ajalt** [comment]
@CasparKielwein sure, the most helpful thing would be to try out this branch and provide feedback on the API/feature set/etc. You can replace your normal clikt dependency with a build of this branch [via JitPack](https://jitpack.io/#ajalt/clikt/configs-SNAPSHOT).

**Comment by CasparKielwein** [comment]
I finally got to play around with it a bit and using the new valueSources seems really straight forward.
The only thing that I tripped on is the name conflict betwee ```<T : CliktCommand> T.context``` and CliktCommand's memberycontext.
When context is not imported, the error message is failry confusing
> Expression 'context' of type 'Context' cannot be invoked as a function. The function 'invoke()' is not found

I am aware, that this was not introducted in this branch, I hadn't used context yet.

**Comment by ajalt** [comment]
Thanks for looking at it! 

I agree that name collision is annoying. I'm going to rename it the next time I make breaking changes.

**Comment by ajalt** [comment]
Closing this PR for now. There are improvements I want to make to the design before merging it. The branch can still be built with JitPack, as described above for people who need it.

**Pull request closed without merging**
