### PR TITLE
Make CompletionGenerator non-internal

### PR DESCRIPTION
**Pull request by tristanlins**
This enables individual generation of the completion.
For example, I would like to provide a separate command for it, such as [kubectl](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#completion) / [helm](https://helm.sh/docs/helm/helm_completion/).

```kotlin
class CompletionCommand : CliktCommand(
    name = "completion",
    help = "Generate completion script."
) {

    val shell by argument("SHELL").choice("bash", "zsh")

    override fun run() {
        val completion = CompletionGenerator.generateCompletion(command = this, zsh = "zsh" == shell)
        throw PrintCompletionMessage(completion, forceUnixLineEndings = true)
    }

}
```

### CODE REVIEW

**Comment by ajalt** [comment]
This would make it difficult to add difficult to add support for more shells in the future. I don't want to have to make a breaking API change to implement #189, for example.

I think a better approach would be to keep `generateCompletion` internal, and instead add public `CompletionGenerator.generateBashCompletion` and `CompletionGenerator.generateZshCompletion` functions that call the internal one. That way we could add `generateFishCompletion` in the future without breaking anything.

**Comment by tristanlins** [comment]
Mh, one method per shell?
A better approach may be to change the method parameter to an enum?
That would be a lot more future proof and using an enum with a `choice` argument is pretty easy :-)

```kt
enum Shell {
    BASH,
    ZSH
}

CompletionGenerator.generateCompletion(command: CliktCommand, shell: Shell = Shell.ZSH): String
```

**Comment by ajalt** [comment]
Using an enum doesn't solve the backwards compatibility problems, since adding a case to the enum would be source incompatible e.g. for anyone using an exhaustive `when` on that enum.

**Comment by tristanlins** [comment]
Okay, api compatibility is a point.
I have updated the PR.

**Pull request merged**
