### PR TITLE
Add echo overload with no parameters

### PR DESCRIPTION
**Pull request by ajalt**

### CODE REVIEW

**Comment by Legion2** [comment]
I was using echo to print boolean values which were automatically converted to strings. Now silently it uses the overloaded version and just prints a newline.
https://github.com/Legion2/open-cue-cli/blob/cd1b64afa7cfcffc0e533321f525066a17ba9d62/src/main/kotlin/io/github/legion2/open_cue_cli/sdk/SdkControl.kt#L16

I only recognized this because I tested the command manually.

**Comment by ajalt** [comment]
@Legion2 That's unfortunate. Thanks for the report. #234  should fix this issue by removing the default parameters from the new function and deprecating it. Let me know if that solution would work for you.

**Comment by Legion2** [comment]
Yes that would work, but as long as the deprecated echo function exist I have to convert the booleans to strings before passing them to echo, else the deprecated version would be used.

@ajalt Nevertheless, thanks for the great project.

**Comment by ajalt** [comment]
@Legion2 Actually, since the overload I'm deprecating has two parameters, calling `echo` with a single boolean will resolve to the normal version, so you won't have to convert it to a string manually.

**Comment by Legion2** [comment]
Ok, I didn't see you removed the default arguments.

**Pull request merged**
