### PR TITLE
Add CliktConsole parameter to TermUi.prompt

### PR DESCRIPTION
**Pull request by guuilp**
When writing unit tests for my ClickCommand which is using `TermUi.prompt() : String?`, I realized that it was impossible to set a custom CliktConsole to it, so I'm adding it.

Please let me know if I missed something on how to contribute to this awesome project!

### CODE REVIEW

**Comment by guuilp** [comment]
I just realized that `CliktCommand` has proxy APIs for most of `TermUi` functions:
- `echo`
- `prompt`
- `confirm`

With the advantage of using `currentContext.console`, which makes it easier to test.

What do you think of adding the missing proxies (`editFile` and `editText`) and make `TermUi` private to the library?

**Comment by ajalt** [comment]
Yes, I think that's a change worth making.

**Comment by guilherme-pereira-ifood** [comment]
Great, I'll work on that 👍

**Comment by guuilp** [comment]
Closing this in favor of #344

**Pull request closed without merging**
